# Custom configuration for Readme-Workflows/recent-activity
max_lines: 8
template: |
  | ğŸ—“ï¸ Date | ğŸ·ï¸ Activity |
  |----------|-------------|
  {% for event in events %}
  | {{ event.created_at | date("Y-%m-%d") }} | {{ event.action }} **{{ event.repo.name }}** |
  {% endfor %}
